In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
file_names = pd.read_csv("D:/hahaton/train.csv")
file_names.head()

                 id  category
0   2_trans_497.csv         1
1   2_trans_483.csv         1
2  2_trans_2396.csv         1
3  2_trans_1847.csv         1
4  2_trans_2382.csv         1

In [36]:
result = []
for i, r in file_names.iterrows():
    df = pd.read_csv("D:/hahaton/data_train/data_train/" + r["id"])
    df["category"] = r["category"]
    result.append(df)
result[0].tail()

           H2        CO      C2H4      C2H2  category
415  0.002276  0.041801  0.004549  0.000343         1
416  0.002281  0.041875  0.004569  0.000344         1
417  0.002285  0.041950  0.004590  0.000344         1
418  0.002290  0.042025  0.004610  0.000345         1
419  0.002294  0.042099  0.004630  0.000345         1

In [37]:
result = pd.concat(result)

In [38]:
result

           H2        CO      C2H4      C2H2  category
0    0.001202  0.029565  0.001069  0.000251         1
1    0.001202  0.029563  0.001068  0.000251         1
2    0.001201  0.029562  0.001066  0.000251         1
3    0.001201  0.029562  0.001064  0.000251         1
4    0.001201  0.029561  0.001063  0.000251         1
..        ...       ...       ...       ...       ...
415  0.001832  0.034432  0.003580  0.000155         1
416  0.001833  0.034493  0.003583  0.000156         1
417  0.001835  0.034553  0.003586  0.000156         1
418  0.001836  0.034614  0.003589  0.000156         1
419  0.001837  0.034674  0.003593  0.000156         1

[882000 rows x 5 columns]

In [11]:
from sklearn.ensemble import GradientBoostingClassifier

In [12]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1, max_depth=1, random_state=2)

In [13]:
y = result.pop('category')
X = result

In [129]:
X

           H2        CO      C2H4      C2H2
0    0.001202  0.029565  0.001069  0.000251
1    0.001202  0.029563  0.001068  0.000251
2    0.001201  0.029562  0.001066  0.000251
3    0.001201  0.029562  0.001064  0.000251
4    0.001201  0.029561  0.001063  0.000251
..        ...       ...       ...       ...
415  0.001832  0.034432  0.003580  0.000155
416  0.001833  0.034493  0.003583  0.000156
417  0.001835  0.034553  0.003586  0.000156
418  0.001836  0.034614  0.003589  0.000156
419  0.001837  0.034674  0.003593  0.000156

[882000 rows x 4 columns]

In [10]:
y

0      1
1      1
2      1
3      1
4      1
      ..
415    1
416    1
417    1
418    1
419    1
Name: category, Length: 882000, dtype: int64

In [96]:
def normalize(X):
    means = []
    stds = []
    for name in ("H2", "CO","C2H4","C2H2"):
        m = np.mean(X[name])
        std = np.std(X[name])
        X[name] = (X[name] - m) / std
        print(m)
        means.append(m)
        stds.append(std)
    return X, means, stds

In [97]:
res, m, s = normalize(X)

0.0024449650638393066
0.02390119200873537
0.006760441133314157
0.00027166287277873865

In [98]:
print(res, m, s)

           H2        CO      C2H4      C2H2
419 -0.148347  1.522949 -0.643663  0.549415
419  0.313481  1.106915 -0.072748 -0.939486
419 -0.618033  1.086548 -1.136554 -0.139882
419 -0.772835  0.346678  0.557197  0.288519
419 -0.347807 -0.818253  1.961354  0.559893
..        ...       ...       ...       ...
419 -0.290522 -1.005242 -0.016697 -0.467615
419 -1.317235  0.996502  0.230033  0.716945
419  1.862296  0.657172 -0.621824  0.146045
419  1.294994 -0.150384 -0.671848  1.356535
419 -0.597418  0.901576 -0.957233 -0.862284

[2100 rows x 4 columns] [0.0024449650638393066, 0.02390119200873537, 0.006760441133314157, 0.00027166287277873865] [0.0010172043332936692, 0.011949365375111131, 0.0033092795342330654, 0.00013422924726218277]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X.index,y,test_size=0.2)
train = X.iloc[X_train]
test = X.iloc[X_test]

In [45]:
y_train

261    4
207    1
384    1
165    1
284    1
      ..
270    1
241    1
85     1
93     1
246    1
Name: category, Length: 705600, dtype: int64

In [109]:
w = np.zeros(len(y_train))
w[y_train==1] =  1. / sum(y_train==1)
w[y_train==2] = 1. / sum(y_train==2)
w[y_train==3] = 1. / sum(y_train==3)
w[y_train==4] = 1. / sum(y_train==4)

In [39]:
print(sum(result["category"]==1))
print(sum(result["category"]==2))
print(sum(result["category"]==3))
print(sum(result["category"]==4))

716100
37380
47460
81060

In [110]:
w

array([0.0007446, 0.0060241, 0.0007446, ..., 0.0007446, 0.0007446,
       0.0007446])

In [200]:
train

               H2        CO      C2H4      C2H2
62124    0.002831  0.019729  0.006862  0.000281
104429   0.002341  0.001235  0.006135  0.000391
2751861  0.003067  0.009158  0.003606  0.000385
2214087  0.001356  0.007881  0.007959  0.000280
1149170  0.001290  0.000920  0.000280  0.000012
...           ...       ...       ...       ...
633469   0.001279  0.032279  0.004297  0.000355
1422273  0.001028  0.003526  0.000413  0.000022
2124960  0.000401  0.006727  0.003781  0.000265
990125   0.002160  0.000339  0.000135  0.000017
29579    0.000602  0.005472  0.007666  0.000241

[2291520 rows x 4 columns]

In [18]:
clf.fit(train, y_train)

GradientBoostingClassifier(learning_rate=1, max_depth=1, random_state=2)

In [19]:
# 1 Ð¿Ð¾Ð¿Ñ‹Ñ‚ÐºÐ°
clf.score(test, y_test)

0.842827626918536

In [24]:
class Logic:
    def load_clf(self):
        filename = "D:/hahaton/clf.sav"
        self.clf = pickle.load(open(filename, 'rb'))
    
    def get_defect(self, values)
        return self.clf.predict(values).tolist()

In [25]:
l = Logic()
l.load_clf()

In [33]:
l.clf.predict([[0.5, 0.5, 0.5, 0.5], [0.5, 0.5, 0.5, 1]]).tolist()

[1, 1]

In [20]:
import pickle

In [21]:
pickle.dump(clf, open("D:/hahaton/clf.sav", 'wb'))

In [18]:
from sklearn import linear_model
reg = linear_model.Ridge(alpha=.5)

In [ ]:
reg.fit(train, y_train)

In [55]:
df_test = pd.read_csv("D:/hahaton/data_test/data_test/2_trans_300.csv")
clf.predict(df_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=int64)

In [54]:
import os

In [58]:
os.listdir("D:/hahaton/data_test/data_test/")

['2_trans_1.csv',
 '2_trans_10.csv',
 '2_trans_1003.csv',
 '2_trans_1004.csv',
 '2_trans_1005.csv',
 '2_trans_1007.csv',
 '2_trans_1008.csv',
 '2_trans_1009.csv',
 '2_trans_1011.csv',
 '2_trans_1014.csv',
 '2_trans_102.csv',
 '2_trans_1024.csv',
 '2_trans_1025.csv',
 '2_trans_1027.csv',
 '2_trans_103.csv',
 '2_trans_1033.csv',
 '2_trans_1036.csv',
 '2_trans_1037.csv',
 '2_trans_1040.csv',
 '2_trans_1048.csv',
 '2_trans_1049.csv',
 '2_trans_1050.csv',
 '2_trans_1051.csv',
 '2_trans_1052.csv',
 '2_trans_1055.csv',
 '2_trans_1056.csv',
 '2_trans_1061.csv',
 '2_trans_1063.csv',
 '2_trans_1064.csv',
 '2_trans_1065.csv',
 '2_trans_107.csv',
 '2_trans_1074.csv',
 '2_trans_1076.csv',
 '2_trans_1077.csv',
 '2_trans_1079.csv',
 '2_trans_1080.csv',
 '2_trans_1081.csv',
 '2_trans_1086.csv',
 '2_trans_1091.csv',
 '2_trans_1095.csv',
 '2_trans_1096.csv',
 '2_trans_110.csv',
 '2_trans_1100.csv',
 '2_trans_1105.csv',
 '2_trans_1106.csv',
 '2_trans_111.csv',
 '2_trans_1111.csv',
 '2_trans_1112.csv',
 '2_trans_1115.csv',
 '2_trans_1116.csv',
 '2_trans_1124.csv',
 '2_trans_1125.csv',
 '2_trans_1128.csv',
 '2_trans_1129.csv',
 '2_trans_1132.csv',
 '2_trans_1134.csv',
 '2_trans_1136.csv',
 '2_trans_1139.csv',
 '2_trans_1140.csv',
 '2_trans_1143.csv',
 '2_trans_1145.csv',
 '2_trans_1154.csv',
 '2_trans_1155.csv',
 '2_trans_1158.csv',
 '2_trans_1159.csv',
 '2_trans_1160.csv',
 '2_trans_1163.csv',
 '2_trans_1170.csv',
 '2_trans_1171.csv',
 '2_trans_1178.csv',
 '2_trans_1180.csv',
 '2_trans_1181.csv',
 '2_trans_1182.csv',
 '2_trans_1183.csv',
 '2_trans_1186.csv',
 '2_trans_1189.csv',
 '2_trans_119.csv',
 '2_trans_1191.csv',
 '2_trans_1192.csv',
 '2_trans_1195.csv',
 '2_trans_1197.csv',
 '2_trans_1199.csv',
 '2_trans_120.csv',
 '2_trans_1205.csv',
 '2_trans_1206.csv',
 '2_trans_1215.csv',
 '2_trans_1216.csv',
 '2_trans_1217.csv',
 '2_trans_1222.csv',
 '2_trans_1223.csv',
 '2_trans_1225.csv',
 '2_trans_1226.csv',
 '2_trans_1231.csv',
 '2_trans_1234.csv',
 '2_trans_1235.csv',
 '2_trans_1237.csv',
 '2_trans_1245.csv',
 '2_trans_1246.csv',
 '2_trans_125.csv',
 '2_trans_1256.csv',
 '2_trans_1257.csv',
 '2_trans_1258.csv',
 '2_trans_1259.csv',
 '2_trans_1260.csv',
 '2_trans_1273.csv',
 '2_trans_128.csv',
 '2_trans_1281.csv',
 '2_trans_1283.csv',
 '2_trans_129.csv',
 '2_trans_1296.csv',
 '2_trans_1299.csv',
 '2_trans_13.csv',
 '2_trans_132.csv',
 '2_trans_1320.csv',
 '2_trans_1321.csv',
 '2_trans_1325.csv',
 '2_trans_1327.csv',
 '2_trans_1333.csv',
 '2_trans_1335.csv',
 '2_trans_1337.csv',
 '2_trans_1338.csv',
 '2_trans_134.csv',
 '2_trans_1340.csv',
 '2_trans_1341.csv',
 '2_trans_1343.csv',
 '2_trans_1353.csv',
 '2_trans_1355.csv',
 '2_trans_136.csv',
 '2_trans_1362.csv',
 '2_trans_1368.csv',
 '2_trans_1370.csv',
 '2_trans_1376.csv',
 '2_trans_1378.csv',
 '2_trans_138.csv',
 '2_trans_1386.csv',
 '2_trans_1391.csv',
 '2_trans_1394.csv',
 '2_trans_1397.csv',
 '2_trans_1403.csv',
 '2_trans_1406.csv',
 '2_trans_1407.csv',
 '2_trans_141.csv',
 '2_trans_1418.csv',
 '2_trans_1423.csv',
 '2_trans_1425.csv',
 '2_trans_1427.csv',
 '2_trans_1429.csv',
 '2_trans_143.csv',
 '2_trans_1435.csv',
 '2_trans_144.csv',
 '2_trans_1445.csv',
 '2_trans_1446.csv',
 '2_trans_145.csv',
 '2_trans_1451.csv',
 '2_trans_1454.csv',
 '2_trans_1455.csv',
 '2_trans_1458.csv',
 '2_trans_1459.csv',
 '2_trans_1462.csv',
 '2_trans_1467.csv',
 '2_trans_147.csv',
 '2_trans_1470.csv',
 '2_trans_1475.csv',
 '2_trans_1476.csv',
 '2_trans_1479.csv',
 '2_trans_1481.csv',
 '2_trans_1485.csv',
 '2_trans_149.csv',
 '2_trans_1491.csv',
 '2_trans_1493.csv',
 '2_trans_1495.csv',
 '2_trans_150.csv',
 '2_trans_1503.csv',
 '2_trans_1506.csv',
 '2_trans_1508.csv',
 '2_trans_1513.csv',
 '2_trans_1515.csv',
 '2_trans_1518.csv',
 '2_trans_1521.csv',
 '2_trans_1524.csv',
 '2_trans_1527.csv',
 '2_trans_1530.csv',
 '2_trans_1531.csv',
 '2_trans_1535.csv',
 '2_trans_1536.csv',
 '2_trans_1538.csv',
 '2_trans_1539.csv',
 '2_trans_154.csv',
 '2_trans_1544.csv',
 '2_trans_1545.csv',
 '2_trans_1546.csv',
 '2_trans_155.csv',
 '2_trans_1550.csv',
 '2_trans_1554.csv',
 '2_trans_1555.csv',
 '2_trans_156.csv',
 '2_trans_1562.csv',
 '2_trans_1564.csv',
 '2_trans_1565.csv',
 '2_trans_1568.csv',
 '2_trans_1576.csv',
 '2_trans_1578.csv',
 '2_trans_1579.csv',
 '2_trans_158.csv',
 '2_trans_1580.csv',
 '2_trans_1582.csv',
 '2_trans_1588.csv',
 '2_trans_159.csv',
 '2_trans_1590.csv',
 '2_trans_1593.csv',
 '2_trans_1594.csv',
 '2_trans_16.csv',
 '2_trans_160.csv',
 '2_trans_1603.csv',
 '2_trans_1604.csv',
 '2_trans_161.csv',
 '2_trans_1613.csv',
 '2_trans_1617.csv',
 '2_trans_1618.csv',
 '2_trans_1619.csv',
 '2_trans_1623.csv',
 '2_trans_1631.csv',
 '2_trans_1632.csv',
 '2_trans_1634.csv',
 '2_trans_1636.csv',
 '2_trans_1637.csv',
 '2_trans_1640.csv',
 '2_trans_1642.csv',
 '2_trans_1647.csv',
 '2_trans_1648.csv',
 '2_trans_1653.csv',
 '2_trans_1655.csv',
 '2_trans_1657.csv',
 '2_trans_1663.csv',
 '2_trans_1665.csv',
 '2_trans_167.csv',
 '2_trans_1672.csv',
 '2_trans_1674.csv',
 '2_trans_1680.csv',
 '2_trans_1685.csv',
 '2_trans_1686.csv',
 '2_trans_1687.csv',
 '2_trans_1688.csv',
 '2_trans_1689.csv',
 '2_trans_1693.csv',
 '2_trans_1696.csv',
 '2_trans_1699.csv',
 '2_trans_17.csv',
 '2_trans_170.csv',
 '2_trans_1700.csv',
 '2_trans_1701.csv',
 '2_trans_1706.csv',
 '2_trans_1708.csv',
 '2_trans_1711.csv',
 '2_trans_1716.csv',
 '2_trans_172.csv',
 '2_trans_1720.csv',
 '2_trans_1725.csv',
 '2_trans_1726.csv',
 '2_trans_1729.csv',
 '2_trans_1731.csv',
 '2_trans_1732.csv',
 '2_trans_1733.csv',
 '2_trans_1737.csv',
 '2_trans_174.csv',
 '2_trans_1740.csv',
 '2_trans_1743.csv',
 '2_trans_1746.csv',
 '2_trans_1752.csv',
 '2_trans_1754.csv',
 '2_trans_1757.csv',
 '2_trans_1758.csv',
 '2_trans_176.csv',
 '2_trans_1761.csv',
 '2_trans_1762.csv',
 '2_trans_1767.csv',
 '2_trans_1768.csv',
 '2_trans_1771.csv',
 '2_trans_1773.csv',
 '2_trans_178.csv',
 '2_trans_1783.csv',
 '2_trans_1785.csv',
 '2_trans_179.csv',
 '2_trans_1797.csv',
 '2_trans_1799.csv',
 '2_trans_180.csv',
 '2_trans_1803.csv',
 '2_trans_1807.csv',
 '2_trans_1810.csv',
 '2_trans_1811.csv',
 '2_trans_1816.csv',
 '2_trans_182.csv',
 '2_trans_1820.csv',
 '2_trans_1821.csv',
 '2_trans_1823.csv',
 '2_trans_1825.csv',
 '2_trans_1826.csv',
 '2_trans_1829.csv',
 '2_trans_1832.csv',
 '2_trans_1833.csv',
 '2_trans_1834.csv',
 '2_trans_1838.csv',
 '2_trans_1841.csv',
 '2_trans_1842.csv',
 '2_trans_1851.csv',
 '2_trans_1852.csv',
 '2_trans_1853.csv',
 '2_trans_1854.csv',
 '2_trans_1855.csv',
 '2_trans_1856.csv',
 '2_trans_1857.csv',
 '2_trans_1865.csv',
 '2_trans_1868.csv',
 '2_trans_1871.csv',
 '2_trans_188.csv',
 '2_trans_1881.csv',
 '2_trans_1882.csv',
 '2_trans_1889.csv',
 '2_trans_1890.csv',
 '2_trans_1891.csv',
 '2_trans_1896.csv',
 '2_trans_190.csv',
 '2_trans_1902.csv',
 '2_trans_1907.csv',
 '2_trans_1915.csv',
 '2_trans_1919.csv',
 '2_trans_192.csv',
 '2_trans_1921.csv',
 '2_trans_1925.csv',
 '2_trans_1926.csv',
 '2_trans_1927.csv',
 '2_trans_1929.csv',
 '2_trans_1932.csv',
 '2_trans_1933.csv',
 '2_trans_1934.csv',
 '2_trans_1937.csv',
 '2_trans_1944.csv',
 '2_trans_1949.csv',
 '2_trans_195.csv',
 '2_trans_1951.csv',
 '2_trans_1954.csv',
 '2_trans_1956.csv',
 '2_trans_1959.csv',
 '2_trans_196.csv',
 '2_trans_1964.csv',
 '2_trans_197.csv',
 '2_trans_1974.csv',
 '2_trans_1977.csv',
 '2_trans_1980.csv',
 '2_trans_199.csv',
 '2_trans_1990.csv',
 '2_trans_1991.csv',
 '2_trans_1992.csv',
 '2_trans_1993.csv',
 '2_trans_1994.csv',
 '2_trans_1995.csv',
 '2_trans_1997.csv',
 '2_trans_200.csv',
 '2_trans_2000.csv',
 '2_trans_2002.csv',
 '2_trans_2004.csv',
 '2_trans_2005.csv',
 '2_trans_2008.csv',
 '2_trans_2010.csv',
 '2_trans_2014.csv',
 '2_trans_2015.csv',
 '2_trans_2018.csv',
 '2_trans_2019.csv',
 '2_trans_202.csv',
 '2_trans_2027.csv',
 '2_trans_203.csv',
 '2_trans_2030.csv',
 '2_trans_2038.csv',
 '2_trans_204.csv',
 '2_trans_2041.csv',
 '2_trans_2049.csv',
 '2_trans_205.csv',
 '2_trans_2053.csv',
 '2_trans_2054.csv',
 '2_trans_2055.csv',
 '2_trans_2060.csv',
 '2_trans_2061.csv',
 '2_trans_2062.csv',
 '2_trans_2066.csv',
 '2_trans_2067.csv',
 '2_trans_2069.csv',
 '2_trans_2071.csv',
 '2_trans_2072.csv',
 '2_trans_2074.csv',
 '2_trans_2077.csv',
 '2_trans_2078.csv',
 '2_trans_2080.csv',
 '2_trans_2082.csv',
 '2_trans_2084.csv',
 '2_trans_2085.csv',
 '2_trans_209.csv',
 '2_trans_2091.csv',
 '2_trans_2097.csv',
 '2_trans_2098.csv',
 '2_trans_2101.csv',
 '2_trans_2102.csv',
 '2_trans_211.csv',
 '2_trans_2110.csv',
 '2_trans_2115.csv',
 '2_trans_2116.csv',
 '2_trans_2117.csv',
 '2_trans_2121.csv',
 '2_trans_2125.csv',
 '2_trans_2126.csv',
 '2_trans_2133.csv',
 '2_trans_2135.csv',
 '2_trans_2136.csv',
 '2_trans_2139.csv',
 '2_trans_214.csv',
 '2_trans_2142.csv',
 '2_trans_2146.csv',
 '2_trans_2150.csv',
 '2_trans_2152.csv',
 '2_trans_2156.csv',
 '2_trans_216.csv',
 '2_trans_2160.csv',
 '2_trans_2163.csv',
 '2_trans_217.csv',
 '2_trans_2170.csv',
 '2_trans_2171.csv',
 '2_trans_2172.csv',
 '2_trans_2179.csv',
 '2_trans_218.csv',
 '2_trans_2181.csv',
 '2_trans_2185.csv',
 '2_trans_2197.csv',
 '2_trans_2198.csv',
 '2_trans_2201.csv',
 '2_trans_2203.csv',
 '2_trans_2206.csv',
 '2_trans_2207.csv',
 '2_trans_2208.csv',
 '2_trans_2209.csv',
 '2_trans_221.csv',
 '2_trans_2212.csv',
 '2_trans_2213.csv',
 '2_trans_2216.csv',
 '2_trans_2218.csv',
 '2_trans_2220.csv',
 '2_trans_2221.csv',
 '2_trans_2226.csv',
 '2_trans_2231.csv',
 '2_trans_2232.csv',
 '2_trans_2233.csv',
 '2_trans_2236.csv',
 '2_trans_2238.csv',
 '2_trans_2239.csv',
 '2_trans_2243.csv',
 '2_trans_2251.csv',
 '2_trans_2254.csv',
 '2_trans_227.csv',
 '2_trans_2272.csv',
 '2_trans_2276.csv',
 '2_trans_2278.csv',
 '2_trans_2290.csv',
 '2_trans_2293.csv',
 '2_trans_23.csv',
 '2_trans_2304.csv',
 '2_trans_2306.csv',
 '2_trans_2308.csv',
 '2_trans_2309.csv',
 '2_trans_2310.csv',
 '2_trans_2313.csv',
 '2_trans_2315.csv',
 '2_trans_2318.csv',
 '2_trans_2319.csv',
 '2_trans_232.csv',
 '2_trans_2328.csv',
 '2_trans_2332.csv',
 '2_trans_2338.csv',
 '2_trans_2343.csv',
 '2_trans_2344.csv',
 '2_trans_2346.csv',
 '2_trans_2349.csv',
 '2_trans_2351.csv',
 '2_trans_2352.csv',
 '2_trans_2357.csv',
 '2_trans_2358.csv',
 '2_trans_2359.csv',
 '2_trans_2361.csv',
 '2_trans_2365.csv',
 '2_trans_2368.csv',
 '2_trans_2371.csv',
 '2_trans_2373.csv',
 '2_trans_2375.csv',
 '2_trans_2385.csv',
 '2_trans_2387.csv',
 '2_trans_2394.csv',
 '2_trans_2395.csv',
 '2_trans_2398.csv',
 '2_trans_2400.csv',
 '2_trans_2404.csv',
 '2_trans_2407.csv',
 '2_trans_241.csv',
 '2_trans_2411.csv',
 '2_trans_2415.csv',
 '2_trans_2428.csv',
 '2_trans_243.csv',
 '2_trans_2430.csv',
 '2_trans_2432.csv',
 '2_trans_2435.csv',
 '2_trans_2437.csv',
 '2_trans_2442.csv',
 '2_trans_2444.csv',
 '2_trans_2445.csv',
 '2_trans_2450.csv',
 '2_trans_2454.csv',
 '2_trans_2455.csv',
 '2_trans_2463.csv',
 '2_trans_2464.csv',
 '2_trans_2468.csv',
 '2_trans_247.csv',
 '2_trans_248.csv',
 '2_trans_2480.csv',
 '2_trans_2481.csv',
 '2_trans_2482.csv',
 '2_trans_2483.csv',
 '2_trans_2488.csv',
 '2_trans_2489.csv',
 '2_trans_2506.csv',
 '2_trans_2510.csv',
 '2_trans_2511.csv',
 '2_trans_2512.csv',
 '2_trans_2513.csv',
 '2_trans_2515.csv',
 '2_trans_2518.csv',
 '2_trans_2522.csv',
 '2_trans_2526.csv',
 '2_trans_2528.csv',
 '2_trans_2529.csv',
 '2_trans_2532.csv',
 '2_trans_2537.csv',
 '2_trans_2540.csv',
 '2_trans_2546.csv',
 '2_trans_2547.csv',
 '2_trans_255.csv',
 '2_trans_2551.csv',
 '2_trans_2556.csv',
 '2_trans_2562.csv',
 '2_trans_2571.csv',
 '2_trans_2575.csv',
 '2_trans_2578.csv',
 '2_trans_2582.csv',
 '2_trans_2591.csv',
 '2_trans_2592.csv',
 '2_trans_2593.csv',
 '2_trans_2594.csv',
 '2_trans_2595.csv',
 '2_trans_2601.csv',
 '2_trans_2602.csv',
 '2_trans_2604.csv',
 '2_trans_2608.csv',
 '2_trans_261.csv',
 '2_trans_2619.csv',
 '2_trans_2620.csv',
 '2_trans_2621.csv',
 '2_trans_2625.csv',
 '2_trans_2627.csv',
 '2_trans_2628.csv',
 '2_trans_2631.csv',
 '2_trans_2634.csv',
 '2_trans_2640.csv',
 '2_trans_2642.csv',
 '2_trans_2645.csv',
 '2_trans_265.csv',
 '2_trans_2650.csv',
 '2_trans_2655.csv',
 '2_trans_2659.csv',
 '2_trans_2671.csv',
 '2_trans_2672.csv',
 '2_trans_2679.csv',
 '2_trans_2680.csv',
 '2_trans_2681.csv',
 '2_trans_2685.csv',
 '2_trans_2687.csv',
 '2_trans_269.csv',
 '2_trans_2691.csv',
 '2_trans_2693.csv',
 '2_trans_2696.csv',
 '2_trans_2698.csv',
 '2_trans_2708.csv',
 '2_trans_2717.csv',
 '2_trans_2726.csv',
 '2_trans_2728.csv',
 '2_trans_2731.csv',
 '2_trans_2734.csv',
 '2_trans_2743.csv',
 '2_trans_2744.csv',
 '2_trans_2749.csv',
 '2_trans_2755.csv',
 '2_trans_2756.csv',
 '2_trans_2757.csv',
 '2_trans_276.csv',
 '2_trans_2760.csv',
 '2_trans_2764.csv',
 '2_trans_2768.csv',
 '2_trans_2772.csv',
 '2_trans_2785.csv',
 '2_trans_2787.csv',
 '2_trans_2796.csv',
 '2_trans_2797.csv',
 '2_trans_2799.csv',
 '2_trans_2804.csv',
 '2_trans_2805.csv',
 '2_trans_2806.csv',
 '2_trans_2815.csv',
 '2_trans_2821.csv',
 '2_trans_2825.csv',
 '2_trans_2827.csv',
 '2_trans_2831.csv',
 '2_trans_2834.csv',
 '2_trans_2845.csv',
 '2_trans_2847.csv',
 '2_trans_2848.csv',
 '2_trans_285.csv',
 '2_trans_2868.csv',
 '2_trans_2870.csv',
 '2_trans_2871.csv',
 '2_trans_2875.csv',
 '2_trans_2879.csv',
 '2_trans_288.csv',
 '2_trans_2887.csv',
 '2_trans_2891.csv',
 '2_trans_2893.csv',
 '2_trans_2896.csv',
 '2_trans_2899.csv',
 '2_trans_29.csv',
 '2_trans_2901.csv',
 '2_trans_2905.csv',
 '2_trans_2909.csv',
 '2_trans_2911.csv',
 '2_trans_2912.csv',
 '2_trans_2913.csv',
 '2_trans_2917.csv',
 '2_trans_2919.csv',
 '2_trans_2921.csv',
 '2_trans_2922.csv',
 '2_trans_2927.csv',
 '2_trans_2929.csv',
 '2_trans_293.csv',
 '2_trans_2930.csv',
 '2_trans_2931.csv',
 '2_trans_2934.csv',
 '2_trans_2935.csv',
 '2_trans_294.csv',
 '2_trans_2943.csv',
 '2_trans_2946.csv',
 '2_trans_2949.csv',
 '2_trans_295.csv',
 '2_trans_2953.csv',
 '2_trans_2954.csv',
 '2_trans_2956.csv',
 '2_trans_2965.csv',
 '2_trans_2966.csv',
 '2_trans_2967.csv',
 '2_trans_2975.csv',
 '2_trans_2977.csv',
 '2_trans_2982.csv',
 '2_trans_2984.csv',
 '2_trans_2986.csv',
 '2_trans_2993.csv',
 '2_trans_2995.csv',
 '2_trans_300.csv',
 '2_trans_301.csv',
 '2_trans_305.csv',
 '2_trans_306.csv',
 '2_trans_309.csv',
 '2_trans_312.csv',
 '2_trans_316.csv',
 '2_trans_317.csv',
 '2_trans_318.csv',
 '2_trans_320.csv',
 '2_trans_323.csv',
 '2_trans_324.csv',
 '2_trans_327.csv',
 '2_trans_33.csv',
 '2_trans_331.csv',
 '2_trans_334.csv',
 '2_trans_335.csv',
 '2_trans_339.csv',
 '2_trans_342.csv',
 '2_trans_344.csv',
 '2_trans_346.csv',
 '2_trans_347.csv',
 '2_trans_353.csv',
 '2_trans_357.csv',
 '2_trans_359.csv',
 '2_trans_361.csv',
 '2_trans_370.csv',
 '2_trans_371.csv',
 '2_trans_378.csv',
 '2_trans_38.csv',
 '2_trans_382.csv',
 '2_trans_385.csv',
 '2_trans_387.csv',
 '2_trans_388.csv',
 '2_trans_394.csv',
 '2_trans_396.csv',
 '2_trans_397.csv',
 '2_trans_404.csv',
 '2_trans_406.csv',
 '2_trans_407.csv',
 '2_trans_414.csv',
 '2_trans_415.csv',
 '2_trans_417.csv',
 '2_trans_418.csv',
 '2_trans_420.csv',
 '2_trans_424.csv',
 '2_trans_426.csv',
 '2_trans_427.csv',
 '2_trans_428.csv',
 '2_trans_43.csv',
 '2_trans_435.csv',
 '2_trans_446.csv',
 '2_trans_447.csv',
 '2_trans_448.csv',
 '2_trans_45.csv',
 '2_trans_455.csv',
 '2_trans_459.csv',
 '2_trans_460.csv',
 '2_trans_461.csv',
 '2_trans_463.csv',
 '2_trans_464.csv',
 '2_trans_467.csv',
 '2_trans_470.csv',
 '2_trans_472.csv',
 '2_trans_477.csv',
 '2_trans_482.csv',
 '2_trans_485.csv',
 '2_trans_486.csv',
 '2_trans_491.csv',
 '2_trans_493.csv',
 '2_trans_495.csv',
 '2_trans_496.csv',
 '2_trans_50.csv',
 '2_trans_504.csv',
 '2_trans_51.csv',
 '2_trans_510.csv',
 '2_trans_511.csv',
 '2_trans_519.csv',
 '2_trans_522.csv',
 '2_trans_527.csv',
 '2_trans_528.csv',
 '2_trans_533.csv',
 '2_trans_534.csv',
 '2_trans_536.csv',
 '2_trans_547.csv',
 '2_trans_550.csv',
 '2_trans_558.csv',
 '2_trans_560.csv',
 '2_trans_562.csv',
 '2_trans_563.csv',
 '2_trans_565.csv',
 '2_trans_573.csv',
 '2_trans_576.csv',
 '2_trans_578.csv',
 '2_trans_586.csv',
 '2_trans_588.csv',
 '2_trans_59.csv',
 '2_trans_590.csv',
 '2_trans_591.csv',
 '2_trans_593.csv',
 '2_trans_596.csv',
 '2_trans_603.csv',
 '2_trans_608.csv',
 '2_trans_610.csv',
 '2_trans_617.csv',
 '2_trans_620.csv',
 '2_trans_625.csv',
 '2_trans_626.csv',
 '2_trans_628.csv',
 '2_trans_629.csv',
 '2_trans_63.csv',
 '2_trans_635.csv',
 '2_trans_636.csv',
 '2_trans_638.csv',
 '2_trans_639.csv',
 '2_trans_641.csv',
 '2_trans_66.csv',
 '2_trans_660.csv',
 '2_trans_663.csv',
 '2_trans_664.csv',
 '2_trans_671.csv',
 '2_trans_676.csv',
 '2_trans_680.csv',
 '2_trans_682.csv',
 '2_trans_683.csv',
 '2_trans_684.csv',
 '2_trans_69.csv',
 '2_trans_693.csv',
 '2_trans_696.csv',
 '2_trans_698.csv',
 '2_trans_70.csv',
 '2_trans_703.csv',
 '2_trans_705.csv',
 '2_trans_708.csv',
 '2_trans_71.csv',
 '2_trans_711.csv',
 '2_trans_719.csv',
 '2_trans_721.csv',
 '2_trans_722.csv',
 '2_trans_729.csv',
 '2_trans_73.csv',
 '2_trans_730.csv',
 '2_trans_731.csv',
 '2_trans_733.csv',
 '2_trans_740.csv',
 '2_trans_745.csv',
 '2_trans_749.csv',
 '2_trans_750.csv',
 '2_trans_752.csv',
 '2_trans_754.csv',
 '2_trans_757.csv',
 '2_trans_758.csv',
 '2_trans_76.csv',
 '2_trans_765.csv',
 '2_trans_772.csv',
 '2_trans_773.csv',
 '2_trans_777.csv',
 '2_trans_780.csv',
 '2_trans_783.csv',
 '2_trans_784.csv',
 '2_trans_785.csv',
 '2_trans_786.csv',
 '2_trans_787.csv',
 '2_trans_788.csv',
 '2_trans_79.csv',
 '2_trans_795.csv',
 '2_trans_803.csv',
 '2_trans_804.csv',
 '2_trans_805.csv',
 '2_trans_81.csv',
 '2_trans_819.csv',
 '2_trans_82.csv',
 '2_trans_821.csv',
 '2_trans_825.csv',
 '2_trans_829.csv',
 '2_trans_830.csv',
 '2_trans_833.csv',
 '2_trans_840.csv',
 '2_trans_842.csv',
 '2_trans_844.csv',
 '2_trans_845.csv',
 '2_trans_851.csv',
 '2_trans_856.csv',
 '2_trans_864.csv',
 '2_trans_868.csv',
 '2_trans_871.csv',
 '2_trans_872.csv',
 '2_trans_873.csv',
 '2_trans_876.csv',
 '2_trans_877.csv',
 '2_trans_878.csv',
 '2_trans_879.csv',
 '2_trans_88.csv',
 '2_trans_883.csv',
 '2_trans_888.csv',
 '2_trans_89.csv',
 '2_trans_895.csv',
 '2_trans_897.csv',
 '2_trans_899.csv',
 '2_trans_9.csv',
 '2_trans_900.csv',
 '2_trans_907.csv',
 '2_trans_909.csv',
 '2_trans_91.csv',
 '2_trans_913.csv',
 '2_trans_916.csv',
 '2_trans_918.csv',
 '2_trans_919.csv',
 '2_trans_922.csv',
 '2_trans_931.csv',
 '2_trans_938.csv',
 '2_trans_939.csv',
 '2_trans_94.csv',
 '2_trans_941.csv',
 '2_trans_945.csv',
 '2_trans_948.csv',
 '2_trans_957.csv',
 '2_trans_966.csv',
 '2_trans_967.csv',
 '2_trans_969.csv',
 '2_trans_97.csv',
 '2_trans_973.csv',
 '2_trans_974.csv',
 '2_trans_977.csv',
 '2_trans_981.csv',
 '2_trans_982.csv',
 '2_trans_985.csv',
 '2_trans_986.csv',
 '2_trans_987.csv',
 '2_trans_990.csv',
 '2_trans_991.csv',
 '2_trans_998.csv',
 '2_trans_999.csv']

In [203]:
test_res = []
for file in os.listdir("D:/hahaton/data_test/data_test/"):
    df_test = pd.read_csv("D:/hahaton/data_test/data_test/"+file)
    r = int(sum(clf.predict(df_test))/len(df_test))
    #r = clf.predict(df_test.iloc[[-1]])
    print(r)
    test_res.append(r)

2
1
1
3
2
1
3
1
1
1
1
1
1
1
2
1
2
1
1
1
1
1
1
1
1
1
1
1
1
1
2
1
1
1
3
1
3
1
1
1
1
1
1
1
1
1
2
1
1
2
3
1
1
1
2
2
1
2
2
1
1
1
2
1
2
1
1
1
1
1
1
2
1
1
2
1
3
2
1
2
1
1
1
2
2
1
1
1
1
1
2
1
1
2
1
2
2
2
1
2
1
1
1
1
1
2
1
2
2
2
1
1
1
1
1
2
1
1
1
3
1
1
1
1
1
1
1
1
1
2
1
1
1
1
1
1
1
1
1
3
3
2
2
2
1
1
2
1
1
1
1
2
1
2
1
1
3
1
1
1
1
1
2
2
1
1
2
1
1
3
1
2
1
1
1
1
2
1
1
1
1
1
1
2
1
1
1
1
1
1
1
2
1
1
1
2
1
1
2
2
1
1
1
2
2
1
1
1
1
1
1
1
2
2
2
1
1
2
1
1
2
1
1
1
1
1
2
3
1
2
1
2
1
1
1
2
1
1
1
3
1
1
2
2
1
1
1
2
1
1
1
1
1
1
1
2
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
1
1
1
1
1
1
1
1
1
1
2
1
1
1
1
1
2
2
3
1
1
1
1
2
1
1
1
1
1
1
1
1
2
2
1
1
2
1
1
1
1
1
1
2
1
1
1
1
1
1
2
2
1
1
1
1
2
1
1
1
2
2
2
1
2
2
1
1
1
1
2
1
2
1
1
2
1
1
2
2
1
1
2
1
1
1
1
1
3
1
2
2
1
2
2
1
2
2
1
2
2
1
1
2
3
1
1
1
2
2
2
1
2
1
1
1
1
2
1
1
1
2
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
1
1
1
3
1
2
2
1
1
2
1
2
2
2
1
1
2
2
1
1
1
1
1
3
1
1
1
1
1
1
1
1
2
1
2
1
1
1
2
1
2
2
2
1
2
1
1
1
1
2
1
1
2
2
2
1
1
1
1
1
2
1
1
1
1
1
2
1
1
1
1
1
2
1
2
2
1
2
1
1
1
1
1
2
1
1
1
1
2
1
1
1
1
1
1
2
2
1
2
1
1
1
1
1
1
2
1
1
1
2
1
1
1
2
2
2
1
1
3
1
1
1
1
1
2
1
2
1
1
3
1
2
1
2
1
1
1
1
1
1
3
1
2
1
1
2
1
1
1
2
1
1
1
1
1
1
1
1
1
1
1
2
3
1
2
2
1
1
1
1
1
1
1
1
1
2
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
1
1
2
1
3
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
2
1
1
2
1
3
1
2
1
1
2
1
2
1
1
1
1
1
1
2
2
1
1
1
2
1
1
1
1
1
1
1
1
1
1
1
1
1
2
1
1
1
1
1
1
1
1
1
2
1
1
1
2
1
1
1
1
1
1
1
1
1
3
1
2
1
2
2
2
2
2
1
1
2
1
2
2
1
1
1
2
1
1
1
2
2
2
1
2
1
1
1
1
1
1
1
2
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
2
1
1
1
1
2
2
1
2
1
1
2
1
2
2
2
1
1
2
1
1
1
1
2
2
2
1
1
2
2
1
1
1
1
1
1
1
2
1
1
1
2
1
1
1
1
1
2
2
1
1
1
2
1
1
1
1
1
1
1
1
1
1
1
1
2
1
2
1
1
3
1
2
1
1
2
1
1
1
1
1
1
2
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
1
1
2
1
1
1
1
1
1
2
1
1
1
1
2
1

In [204]:
df = pd.DataFrame()
df["id"] = os.listdir("D:/hahaton/data_test/data_test/")
df["category"] = test_res

In [205]:
df

                   id  category
0       2_trans_1.csv         2
1      2_trans_10.csv         1
2    2_trans_1003.csv         1
3    2_trans_1004.csv         3
4    2_trans_1005.csv         2
..                ...       ...
895   2_trans_987.csv         1
896   2_trans_990.csv         1
897   2_trans_991.csv         1
898   2_trans_998.csv         2
899   2_trans_999.csv         1

[900 rows x 2 columns]

In [206]:
df.to_csv("D:/hahaton/test.csv", index=False)

In [65]:
    result.describe()

                 H2            CO          C2H4          C2H2
count  8.820000e+05  8.820000e+05  8.820000e+05  8.820000e+05
mean   1.770710e-03  1.707246e-02  4.809312e-03  1.937473e-04
std    9.164189e-04  1.023960e-02  2.868620e-03  1.154310e-04
min    1.784526e-08  1.496807e-08  7.865758e-09  7.897411e-11
25%    1.022670e-03  8.308363e-03  2.383507e-03  9.677079e-05
50%    1.796790e-03  1.690838e-02  4.763536e-03  1.938408e-04
75%    2.509042e-03  2.530238e-02  7.173094e-03  2.868212e-04
max    5.622305e-03  5.747638e-02  1.539378e-02  6.707065e-04

In [61]:
len(os.listdir("D:/hahaton/data_test/data_test/"))

900

In [57]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier()

In [63]:
sgd_clf.fit(train, y_train, sample_weight=w)

SGDClassifier()

In [65]:
sgd_clf.score(test, y_test)

0.8112925170068027

705600

In [6]:
import imblearn

In [7]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [14]:
#oversample = SMOTE()
undersample = RandomUnderSampler(sampling_strategy='majority')
#oversample = RandomOverSampler(sampling_strategy='minority')
#X, y = oversample.fit_resample(X, y)
X, y = undersample.fit_resample(X, y)

In [216]:
X

               H2        CO      C2H4      C2H2
0        0.001202  0.029565  0.001069  0.000251
1        0.001202  0.029563  0.001068  0.000251
2        0.001201  0.029562  0.001066  0.000251
3        0.001201  0.029562  0.001064  0.000251
4        0.001201  0.029561  0.001063  0.000251
...           ...       ...       ...       ...
1560715  0.001726  0.001647  0.000602  0.000018
1560716  0.001806  0.000017  0.000151  0.000011
1560717  0.002437  0.001495  0.000504  0.000007
1560718  0.001624  0.002799  0.000690  0.000037
1560719  0.000823  0.000800  0.000311  0.000019

[1560720 rows x 4 columns]